# Generated by Django 5.2.4 on 2025-07-20 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TenantConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(max_length=100, unique=True)),
                ('idp_provider', models.CharField(max_length=64)),
                ('client_id', models.CharField(max_length=255)),
                ('client_secret', models.CharField(max_length=255)),
                ('issuer', models.CharField(max_length=100)),
                ('audience', models.CharField(max_length=100)),
                ('redirect_uri', models.URLField()),
                ('idp_metadata_url', models.URLField(blank=True, null=True)),
                ('frontend_post_login_url', models.URLField()),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
    ]
