# Generated by Django 5.2.4 on 2025-07-23 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenantconfig',
            old_name='idp_metadata_url',
            new_name='idp_authorization_url',
        ),
        migrations.AddField(
            model_name='tenantconfig',
            name='frontend_post_logout_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenantconfig',
            name='idp_logout_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenantconfig',
            name='idp_token_endpoint_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
