# Generated by Django 5.2.4 on 2025-08-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0003_tenantconfig_idp_jwks_uri'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantconfig',
            name='allowed_email_domains',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
